public class RepMaxGuiPRFinder extends javax.swing.JFrame {
    double maxweight;
    int maxreps;
    double output;
    
    /**
     * Creates new form RepMaxGuiPRFinder
     */
    public RepMaxGuiPRFinder() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        weight = new javax.swing.JTextField();
        reps = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        result = new java.awt.Label();
        warning = new java.awt.Label();
        enter = new javax.swing.JButton();
        repTable = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        Home = new javax.swing.JMenuItem();
        reptablemenu = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(248, 341));
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Max Weight Finder");

        weight.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        weight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightActionPerformed(evt);
            }
        });

        reps.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        reps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter your working set");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Weight");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Reps");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setText("Your max weight is:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        result.setAlignment(java.awt.Label.RIGHT);
        result.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        warning.setAlignment(java.awt.Label.CENTER);
        warning.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        enter.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        enter.setText("Enter");
        enter.setMaximumSize(new java.awt.Dimension(88, 22));
        enter.setMinimumSize(new java.awt.Dimension(88, 22));
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });

        repTable.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        repTable.setText("Rep Table");
        repTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repTableActionPerformed(evt);
            }
        });

        jMenu3.setText("Menu");

        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jMenu3.add(Home);

        reptablemenu.setText("Rep Table");
        reptablemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reptablemenuActionPerformed(evt);
            }
        });
        jMenu3.add(reptablemenu);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(warning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(weight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(reps, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enter, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addGap(23, 23, 23))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repTable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6))
                    .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RepMaxGuiHome().setVisible(true);
                new RepMaxGuiPRFinder().setVisible(false);
            }
        });
    }//GEN-LAST:event_HomeActionPerformed

    private void weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightActionPerformed

    private void repsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_repsActionPerformed

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        // TODO add your handling code here:
        String repsString = reps.getText();
        String weightString = weight.getText();
        int repsInt = 0;
        double weightInt = 0;
        warning.setText("");
        try{
            repsInt = Integer.valueOf(repsString);
            if (0 >= repsInt){
                warning.setText("Please input a number > 0");
            }
            if (12 < repsInt){
                warning.setText("Retry with heigher weight so reps < 13");
            }
            
        }
        catch (NumberFormatException ex){
            warning.setText("Please input a number for reps");
        }
        try{
            weightInt = Integer.valueOf(weightString);
            if (0 >= weightInt){
                warning.setText("Please input a number > 0");
            }
            
        }
        catch (NumberFormatException ex){
            warning.setText("Please input a number for weight");
        }       
        maxweight = findMax(weightInt,repsInt);
        maxweight = (double) (Math.round(maxweight*10.0)/10.0);
        result.setText(String.valueOf(maxweight));
        
    }//GEN-LAST:event_enterActionPerformed

    private void reptablemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reptablemenuActionPerformed
         // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RepTable().setVisible(true);
                new RepMaxGuiHome().setVisible(false);
            }
        });
    }//GEN-LAST:event_reptablemenuActionPerformed

    private void repTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repTableActionPerformed
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RepMaxGuiPRFinder().setVisible(false);
                new RepTable().setVisible(true);
            }
        });
    }//GEN-LAST:event_repTableActionPerformed
public static double findMax (double weight, int reps){
        double max =0;
        switch (reps) {
        case 1:
            max = weight;
            break;
        case 2:
            max = weight/.9722;
            break;
        case 3:
            max = weight/.9444;
            break;
        case 4:
            max = weight/.9166;
            break;
        case 5:
            max = weight/.8888;
            break;
        case 6:
            max = weight/.861;
            break;
        case 7:
            max = weight/.8332;
            break;
        case 8:
            max = weight/.8054;
            break;
        case 9:
            max = weight/.7767;
            break;
        case 10:
            max = weight/.750;
            break;
        case 11:
            max = weight /.7317;
            break;
        case 12:
            max = weight /.7143;
            break;
        }
        return max;
    }
    /**
     * @param args the command line arguments
     */
 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Home;
    private javax.swing.JButton enter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JButton repTable;
    private javax.swing.JTextField reps;
    private javax.swing.JMenuItem reptablemenu;
    private java.awt.Label result;
    private java.awt.Label warning;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}