public class RepTable extends javax.swing.JFrame {
    double maxweight;
    int maxreps;
    double output;
    /**
     * Creates new form RepTable
     */
    public RepTable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        reptableobject = new javax.swing.JTable();
        weight = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        reps = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        warning = new java.awt.Label();
        enter = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        Home = new javax.swing.JMenuItem();
        rmf = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(248, 341));
        setPreferredSize(new java.awt.Dimension(248, 364));
        setResizable(false);

        reptableobject.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        reptableobject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Weight", "Reps"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        reptableobject.setMinimumSize(new java.awt.Dimension(30, 150));
        reptableobject.setPreferredSize(new java.awt.Dimension(150, 189));
        reptableobject.setRowHeight(15);
        reptableobject.setShowHorizontalLines(true);
        reptableobject.setShowVerticalLines(true);
        jScrollPane1.setViewportView(reptableobject);

        weight.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        weight.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Import your working set");

        reps.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        reps.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Weight");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Reps");

        warning.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        enter.setText("Enter");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });

        menu.setText("Menu");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        menu.add(Home);

        rmf.setText("Max Weight Finder");
        rmf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmfActionPerformed(evt);
            }
        });
        menu.add(rmf);

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(reps, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(enter))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(warning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enter))
                .addGap(0, 0, 0)
                .addComponent(warning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuActionPerformed

    private void rmfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmfActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RepMaxGuiPRFinder().setVisible(true);
                new RepTable().setVisible(false);
            }
        });
    }//GEN-LAST:event_rmfActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RepMaxGuiHome().setVisible(true);
                new RepTable().setVisible(false);
            }
        });
    }//GEN-LAST:event_HomeActionPerformed

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        String repsString = reps.getText();
        String weightString = weight.getText();
        int repsInt = 0;
        double weightInt = 0;
        warning.setText("");
        try{
            repsInt = Integer.valueOf(repsString);
            if (0 >= repsInt){
                warning.setText("Please input a number > 0");
            }
            if (12 < repsInt){
                warning.setText("Retry with heigher weight so reps < 13");
            }
            
        }
        catch (NumberFormatException ex){
            warning.setText("Please input a number for reps");
        }
        try{
            weightInt = Integer.valueOf(weightString);
            if (0 >= weightInt){
                warning.setText("Please input a number > 0");
            }
            
        }
        catch (NumberFormatException ex){
            warning.setText("Please input a number for weight");
        }       
        maxweight = findMax(weightInt,repsInt);
        maxweight = (double) (Math.round(maxweight*10.0)/10.0);
               // TODO add your handling code here:
               
        double weightrange[] = new double[12];
        for (int i = 1; i<13;i++){
            double reps = findReps(maxweight,i);
            reps = (double) (Math.round(reps*10.0)/10.0);
            
            weightrange[i-1] = reps;
        }
        double data[][] = new double[12][2];
        for (int i = 1; i<13;i++){
            data[i-1][0] = weightrange[i-1];
            data[i-1][1] = i;
        }    
        String columns[] = {"Weight", "Reps"};
        for(int i = 1;i<13;i++){
        reptableobject.setValueAt(data[i-1][0],i-1,0);
        reptableobject.setValueAt(data[i-1][1],i-1,1);
        
        }

        
    }//GEN-LAST:event_enterActionPerformed
public static double findMax (double weight, int reps){
        double max =0;
        switch (reps) {
        case 1:
            max = weight;
            break;
        case 2:
            max = weight/.9722;
            break;
        case 3:
            max = weight/.9444;
            break;
        case 4:
            max = weight/.9166;
            break;
        case 5:
            max = weight/.8888;
            break;
        case 6:
            max = weight/.861;
            break;
        case 7:
            max = weight/.8332;
            break;
        case 8:
            max = weight/.8054;
            break;
        case 9:
            max = weight/.7767;
            break;
        case 10:
            max = weight/.750;
            break;
        case 11:
            max = weight /.7317;
            break;
        case 12:
            max = weight /.7143;
            break;
        }
        return max;
    }
public static double findReps (double weight, int reps){
        double max =0;
        switch (reps) {
        case 1:
            max = weight;
            break;
        case 2:
            max = weight*.9722;
            break;
        case 3:
            max = weight*.9444;
            break;
        case 4:
            max = weight*.9166;
            break;
        case 5:
            max = weight*.8888;
            break;
        case 6:
            max = weight*.861;
            break;
        case 7:
            max = weight*.8332;
            break;
        case 8:
            max = weight*.8054;
            break;
        case 9:
            max = weight*.7767;
            break;
        case 10:
            max = weight*.750;
            break;
        case 11:
            max = weight *.7317;
            break;
        case 12:
            max = weight *.7143;
            break;
        }
        return max;
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Home;
    private javax.swing.JButton enter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenu menu;
    private javax.swing.JTextField reps;
    private javax.swing.JTable reptableobject;
    private javax.swing.JMenuItem rmf;
    private java.awt.Label warning;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}
